image: alpine/edge
packages:
  - go
  - rsync
  - sqlite
sources:
  - https://github.com/sauerbraten/maitred.git
environment:
  DEPLOY: p1x.pw
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81 # ci@p1x.pw ssh key
tasks:
  - build: |
      cd maitred
      make clean
      make all
  - deploy: |
      cd maitred
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'mkdir -p ~/maitred'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall maitred || true'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq maitred migrations ci@$DEPLOY:~/maitred/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd maitred; nohup ./maitred >> log.txt 2>&1 &'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall stats || true'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq stats api_config.json public ci@$DEPLOY:~/maitred/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd maitred; nohup ./stats >> log.api.txt 2>&1 &'