image: alpine/edge
packages:
  - go
  - rsync
  - sqlite
sources:
  - https://github.com/sauerbraten/maitred.git
environment:
  DEPLOY: p1x.pw
  GOPATH: $HOME
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81
tasks:
  - prepare_gopath: |
      mkdir -p src/github.com/sauerbraten
      mv maitred src/github.com/sauerbraten/
  - build: |
      cd src/github.com/sauerbraten/maitred
      make clean
      make all
  - deploy: |
      cd src/github.com/sauerbraten/maitred
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'mkdir -p ~/maitred'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall maitred || true'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq maitred maitred.sqlite ci@$DEPLOY:~/maitred/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd maitred; export STATSAUTH_ADMIN_NAME=p1x.pw STATSAUTH_ADMIN_KEY=$(cat .statsauth_admin_key); nohup ./maitred >> log.txt 2>&1 &'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall stats || true'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq stats api_config.json ci@$DEPLOY:~/maitred/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd maitred; nohup ./stats >> log.api.txt 2>&1 &'