image: alpine/edge
packages:
  - go
  - rsync
sources:
  - https://github.com/sauerbraten/maitred.git
environment:
  DEPLOY: p1x.pw
  GOPATH: $HOME
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81
tasks:
  - prepare_gopath: |
      mkdir -p src/github.com/sauerbraten
      mv maitred src/github.com/sauerbraten/
  - build: |
      cd src/github.com/sauerbraten/maitred/cmd/maitred
      go get
      go build
  - deploy: |
      cd src/github.com/sauerbraten/maitred
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'mkdir -p ~/maitred'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq maitred.sqlite.schema ci@$DEPLOY:~/maitred/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd maitred; if [ ! -f maitred.sqlite ] ; then sqlite3 maitred.sqlite < maitred.sqlite.schema ; fi'
      cd cmd/maitred
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq maitred ci@$DEPLOY:~/maitred/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall maitred || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd maitred; nohup ./maitred >> log.txt 2>&1 &'
