image: alpine/latest
packages:
  - git
  - go
  - make
  - rsync
  - sqlite
sources:
  - https://github.com/sauerbraten/maitred.git
environment:
  DEPLOY: p1x.pw
  GOFLAGS: '-mod=vendor'
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81 # ci@p1x.pw ssh key
tasks:
  - build: |
      cd maitred
      make all
  - deploy_master: |
      cd maitred
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'mkdir -p ~/maitred'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq maitred migrations ci@$DEPLOY:~/maitred/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall maitred || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd maitred; nohup ./maitred >> log.txt 2>&1 &'
  - deploy_api: |
      cd maitred
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'mkdir -p ~/stats'
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq stats migrations public api_config.json ci@$DEPLOY:~/stats/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall stats || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd stats; nohup ./stats >> log.api.txt 2>&1 &'
